name: dailytweetLike

on:
  repository_dispatch:
    types: [tweetshortcode]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'

      - name: Create
        run: |
            yesterday=$(TZ=Asia/Tokyo date --date '1 day ago' "+%Y%m%d")
            yesterdayyear=$(TZ=Asia/Tokyo date --date '1 day ago' "+%Y")
            yesterdaymonthday=$(TZ=Asia/Tokyo date --date '1 day ago' "+%m"%d)
            hugo new --kind tweets ./tweets/$yesterdayyear/$yesterdaymonthday.md
            cat ./content/tweets/$yesterdayyear/$yesterdaymonthday.md
      - name: edit
        run: |            
            yesterday=$(TZ=Asia/Tokyo date --date '1 day ago' "+%Y%m%d")
            yesterdayyear=$(TZ=Asia/Tokyo date --date '1 day ago' "+%Y")
            yesterdaymonthday=$(TZ=Asia/Tokyo date --date '1 day ago' "+%m"%d)
            echo -e $yesterday'に行ったツイートです。\n<!--more-->'>> ./content/tweets/$yesterdayyear/$yesterdaymonthday.md
            echo '${{ toJSON(github.event.client_payload) }}' |jq -r .tweets[]|awk '{printf "{{<tweetlike %s>}}\n\n",$0}'>> ./content/tweets/$yesterdayyear/$yesterdaymonthday.md
      - name: push
        env:
            PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
            yesterday=$(TZ=Asia/Tokyo date --date '1 day ago' "+%Y%m%d")
            yesterdayyear=$(TZ=Asia/Tokyo date --date '1 day ago' "+%Y")
            yesterdaymonthday=$(TZ=Asia/Tokyo date --date '1 day ago' "+%m"%d)
            /usr/bin/git add ./content/tweets/$yesterdayyear/$yesterdaymonthday.md
            /usr/bin/git config user.name $GITHUB_ACTOR
            /usr/bin/git config user.email $GITHUB_ACTOR@users.noreply.github.com
            /usr/bin/git commit -m "$yesterdayのツイートまとめ https://mhffdq.github.io/tweets/$yesterdayyear/$yesterdaymonthday.md"
            /usr/bin/git push https://x-access-token:$PUSH_TOKEN@github.com/mhffdq/mhffdq.github.io.git main
