name: dailytweetLike

on:
  repository_dispatch:
    types: [tweetshortcode]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'

      - name: Create
        run: |
            yesterday=$(TZ=Asia/Tokyo date --date '1 day ago' "+%Y%m%d")
            yesterdayyear=$(TZ=Asia/Tokyo date --date '1 day ago' "+%Y")
            yesterdaymonthday=$(TZ=Asia/Tokyo date --date '1 day ago' "+%m"%d)
            hugo new --kind tweets ./tweets/$yesterdayyear/$yesterdaymonthday.md
            mkdir -p ./static/tweets/$yesterdayyear/
            cat ./content/tweets/$yesterdayyear/$yesterdaymonthday.md
            mv ./content/tweets/$yesterdayyear/$yesterdaymonthday.md ./static/tweets/$yesterdayyear/
      - name: edit
        run: |            
            yesterday=$(TZ=Asia/Tokyo date --date '1 day ago' "+%Y%m%d")
            yesterdayyear=$(TZ=Asia/Tokyo date --date '1 day ago' "+%Y")
            yesterdaymonthday=$(TZ=Asia/Tokyo date --date '1 day ago' "+%m"%d)
            echo -e $yesterday'に行ったツイートです。\n<!--more-->'>> ./static/tweets/$yesterdayyear/$yesterdaymonthday.md
            len=$(echo '${{ toJSON(github.event.client_payload) }}' |jq .tweets|jq length)
            echo $len
            for i in $( seq 0 $(($len - 1)) ); do
            echo '${{ toJSON(github.event.client_payload) }}'|jq -r .tweets[$i]|echo -n "{{<tweetlike $(cat)>}}";echo;echo;  done>> ./static/tweets/$yesterdayyear/$yesterdaymonthday.md
      - name: push
        env:
            PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
            yesterday=$(TZ=Asia/Tokyo date --date '1 day ago' "+%Y%m%d")
            yesterdayyear=$(TZ=Asia/Tokyo date --date '1 day ago' "+%Y")
            yesterdaymonthday=$(TZ=Asia/Tokyo date --date '1 day ago' "+%m"%d)
            /usr/bin/git add ./static/tweets/$yesterdayyear/$yesterdaymonthday.md
            /usr/bin/git config user.name $GITHUB_ACTOR
            /usr/bin/git config user.email $GITHUB_ACTOR@users.noreply.github.com
            /usr/bin/git commit -m "$yesterdayのツイートまとめ https://mhffdq.github.io/tweets/$yesterdayyear/$yesterdaymonthday/"
            /usr/bin/git push https://x-access-token:$PUSH_TOKEN@github.com/mhffdq/mhffdq.github.io.git main
