name: dailytweet

on:
  repository_dispatch:
    types: [maketweet]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'

      - name: Create
        run: |
            today=$(date "+%Y%m%d")
            hugo new ./post/tweets/$today.md
      - name: edit
        run: |
            today=$(date "+%Y%m%d")
            echo '${{ toJSON(github.event.client_payload) }}' |jq -r ' .[]'>> ./content/post/tweets/$today.md
      - name: push
        run: |
            today=$(date "+%Y%m%d")
            /usr/bin/git add ./content/post/tweets/$today.md
            /usr/bin/git config user.name $GITHUB_ACTOR
            /usr/bin/git config user.email $GITHUB_ACTOR@users.noreply.github.com
            /usr/bin/git commit -m "https://mhffdq.github.io/post/tweets/$today.md"
            /usr/bin/git push origin main
