name: posttest

on:
  repository_dispatch:
    types: [posttest]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: edit
        run: |  
            echo '${{ toJSON(github.event.client_payload) }}' |jq .tweets[]
            echo $len
            for i in $( seq 0 $(($len - 1)) ); do
            echo '${{ toJSON(github.event.client_payload) }}'|jq .tweets[$i]|echo -n "{{<tweetlike $(cat)>}}";echo;echo;
            done
    
