name: PostTweet

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: PostTweet
      env:
          SUPER_SECRET: ${{ secrets.WEBHOOKURL }}
      run: curl -X POST -H "Content-Type&#58; application/json" -d '{"value1":"tweet $GITHUB_RUN_NUMBER" }' ${{ env.SUPER_SECRET }}
      
