name: PostTweet

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: PostTweet
      env:
          SUPER_SECRET: ${{ secrets.WEBHOOKURL }}
          ContType: "Content-Type&#58; application/json"
      run: curl -X POST -H ${{ env.ContType }} -d '{"value1":"tweet ${{ env.GITHUB_RUN_NUMBER}}" }' ${{ env.SUPER_SECRET }}
      
